// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprjz0gqjBB8D6Y1DLeRBZdkzhvrBCB1k',
    appId: '1:238497560658:web:20f816784c65ce3bc8078b',
    messagingSenderId: '238497560658',
    projectId: 'btll-26137',
    authDomain: 'btll-26137.firebaseapp.com',
    storageBucket: 'btll-26137.appspot.com',
    measurementId: 'G-9GTGWNBTL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDadv4JjuqOqYULSz6VBpBnzN9x4DSFzB0',
    appId: '1:238497560658:android:b299bb13b8b1d352c8078b',
    messagingSenderId: '238497560658',
    projectId: 'btll-26137',
    storageBucket: 'btll-26137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QtGQ5ZBU1tloyvUqcR5NF1jF_-XUpGo',
    appId: '1:238497560658:ios:7b2c1858a4afe470c8078b',
    messagingSenderId: '238497560658',
    projectId: 'btll-26137',
    storageBucket: 'btll-26137.appspot.com',
    iosBundleId: 'com.example.btl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QtGQ5ZBU1tloyvUqcR5NF1jF_-XUpGo',
    appId: '1:238497560658:ios:f0b62f30cd19581bc8078b',
    messagingSenderId: '238497560658',
    projectId: 'btll-26137',
    storageBucket: 'btll-26137.appspot.com',
    iosBundleId: 'com.example.btl.RunnerTests',
  );
}
